---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
spec:
  chart:
    spec:
      chart: rancher
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
  interval: 10m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    hostname: rancher.hellhe.im
    bootstrapPassword: CHANGEME
    # ingress:
    #   enabled: true
    #   ingressClassName: nginx
    #   tls:
    #     source: secret
    #     secretName: ${LETSENCRYPT_CERT}
