---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rancher
  namespace: flux-system
spec:
  targetNamespace: base
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  prune: true
  path: ./kubernetes/apps/cattle-system/rancher/app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # wait for the deployment to be ready before moving on
  interval: 10m
  retryInterval: 1m
  timeout: 10m
