apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:8M+0XvzZnwx9lOgCSmolA1n2FwN5gibHxRmHGokof4e+/8JwsS3gkg==,iv:Yhd1saX+Gb6XktySypYbyrANcmCg+ZL8WGaNroJLDnw=,tag:YTu893yfnk6A0xZY4EWVkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d6gejrkp4u0cjd4ay5uq6vc3n7vvfyvwjkqsqpengytteplvrvtqk683q5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZWhYdnhhcGoydExXUnNK
            MjJlMUt3M3dTNHIwbEhJd2hFNDhDbTVmbldZCm9jYmxwMjRVWmp1R2gwV2dHRXo5
            KzZxSmhxczZ1dGkxMC9Rc0lQR24wdVEKLS0tIHVxSzY4NDYrcnkzVDI2WXN2cmF3
            ejZSdGZtb3o3K3V1WWkzcjV4N1hJYU0KeobC1I3U+/QYKthhvOgpry0MialrblUz
            1iYlP6cRtE9Qh8mKiHYW1PJeZ3vHcWCXviZbWC7pdeJommQKXzrgSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-19T20:04:09Z"
    mac: ENC[AES256_GCM,data:fLozU9bK8FUl8tc1HQdwmJFDXJSml3UgpWCvf6nNTGACrm6d3f0jYjVFwDeQD5NA+zALP5i5TXdSrTnBCcW4blXj3kTbcTYG/OyIYou0E98mVksDlSvgG2TZzy9NdxkFm3Sz/hcxPlcg0HCpVGyk8u6FE9CdV3ndl6B8kOF0TNU=,iv:4wHYSfOXH0P4OksMnpxm86uiqkg1K+ZmsT3rNKpWgak=,tag:U9V3sYaro4UijC4eoibgFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
