apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:BEG/kZWd55ML5ZWI7uermJ5BrDftNTyJZ1OOo2pyqFJAZRnRVutm4A==,iv:TkclXwW2Bmuhjz4nPcowHZp3Ov4WBvZRlJ9tluYczEA=,tag:zB6vDnIWTzV3CqlYn7XHHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d6gejrkp4u0cjd4ay5uq6vc3n7vvfyvwjkqsqpengytteplvrvtqk683q5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBS3VWb3pDMGgvdXp5RWND
            U3pzaW1aTm5jWWpSWEkySXBlRVhHV1M0bFZvCmFaZjB1ekhPQStCS29HNFFsaTE2
            VDRVVHBIWE5MNWxrWHF5VDYvcWtNMVkKLS0tIHErTlBrUDVEUjZ4azBLMVlsQi9p
            YVhsZDNIdUpzZW5kUm9PZG1HSGxjUVkKUvbjVFtjV2IxaacOKQSHq7Ldf/p8yQTV
            7s46Lsj+OKr35/d08uIJaGoPY8TzGoYm3L/ghZCse/G9HnQeMe22SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-28T12:06:43Z"
    mac: ENC[AES256_GCM,data:dWTXBSvTU8/hXRZIy/PkC5a4bvF0C9qIVb6PFPx+diFJsFDlhVNLbeP3Jt1tQhQvVaRY4JM6iPx7VnutfQOtUkiVuqw7tS9PX3Qsyi1EI1fmt6dRHAYzjgRUJW8tsiTnuRy27+CowffwdjoSO7ZZ4kVSCyP7KzgB4Q3qGrjpjkQ=,iv:+auYMO5zmx6n9vT5IsS5CemhJYxiRBXebyhhNH4QGEQ=,tag:JLJngLTQ6C2hoMv9EzNt2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
