apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Fte7WQaRgzb45xEMv7IWLNSBL/+wsGS/nW7hEAKtesHEq76xY2C9+Q==,iv:Hu6QyJ96l8vGxdpLryjRE3OW1hRUYuVEAAKpiz4aJj0=,tag:Dn9N6OOU9pHEnUrKEaXyEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d6gejrkp4u0cjd4ay5uq6vc3n7vvfyvwjkqsqpengytteplvrvtqk683q5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxelZXY0ZVWTNkcHdDZXJr
            ZEM1RjM3bzlKTURlYXhlbmMxdDVGL1hjQTE0CndzM3JKWS91L1d3eHlyQ3VrT05p
            ZXc5Sjh0MDQ3QVVpOEVOT0RvV0xmcXMKLS0tIENpU2dBM0t3cmUrc2FHQm4yUitS
            bVFUUXkxRmFuTjkybXlOMjVsZDlMbVEKezjIQUrKvBSYgqo3Q+0kMs/KD129o8nD
            pohK/ZhQ2aRG81N57Bl3+DAKhTGikrMqpXT2ZMnOWsEoEx6LtM4+CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-28T12:06:43Z"
    mac: ENC[AES256_GCM,data:bQMbwR6Gks9/Hod6032yK3YyLxGNMkx0u5wD2B2ENpRtX+3Xt1RgEHQUtGtePlM7MiqBO4Q2iRhEoCQ7jXBZ4WVhGZ4zdoVakI8rZFhLVSqxaYzhoPpuhI34NuOxAXXSq1l/BhKMbkHxlZqHL4y7dVFnCuk1XwisZcdA+fbmx1c=,iv:KTYn+kdRpG7e/Zra97iqYFWSdoMik4+aSYBKkrBK0rg=,tag:nbumXLYVy5CmK0iPKw/npQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
